add_newline = true
format = "$hostname $username $directory $docker_context $rust $nodejs $python $git_branch $git_status\n$nix_shell $container $character"
palette = "catppuccin_mocha"

[battery]
disabled = true

[character]
error_symbol = "[ï‘„ ó°…™ ](bold fg:#f38ba8)"
success_symbol = "[ï‘„ ï‚© ](bold fg:#cba6f7)"

[container]
format = "[$symbol](fg:#f38ba8) [$name](fg:#89dceb)"
symbol = "ó°–"

[directory]
format = "([ @ ](bg:default fg:#f38ba8) [$path ]($style))"
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:default fg:default"
truncation_length = 6
truncation_symbol = "â€¢â€¢/"

[directory.substitutions]
Desktop = " ï’© "
Documents = " ï’¥ "
Downloads = " ï‰ "
GitHub = "îœ¥"
Music = " ó°ˆ "
Pictures = " ï "
Videos = " ï”¬ "

[docker_context]
format = "[$symbol ](blue)"
symbol = "ïŒˆ "

[git_branch]
format = "[[ ïˆ  on](fg:white) $symbol $branch ](fg:purple)(:$remote_branch)"
style = "bold green"
symbol = "ó°˜¬"
truncation_length = 4
truncation_symbol = "â€¦/"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
conflicted = "ğŸ³"
deleted = "ï€” "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
format = "[$all_status$ahead_behind]($style) "
modified = "ï„ "
renamed = "ó°–· "
staged = "[++\\($count\\)](green)"
stashed = "ó°— "
style = "bold green"
untracked = "ï”© "
up_to_date = "ï† "

[hostname]
disabled = false
format = "[â€¢$hostname](bg:default fg:#cdd6f4)"
ssh_only = true
trim_at = ".companyname.com"

[lua]
format = "[$symbol ](blue)"
symbol = "ó°¢± "

[nix_shell]
disabled = false
format = "[$symbol]($style)"
style = "bg:default fg:blue"
symbol = "ïŒ“ "

[nodejs]
format = "[$symbol ](yellow)"
symbol = "î "

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[python]
format = '[via [$symbol](fg:#f5c2e7) ([$version](fg:#cdd6f4)) ([$virtualenv](fg:#a6e3a1))]($style)'
style = "bg:default fg:default"
symbol = "îœ¼"

[rust]
symbol = "ğŸ¦€"
style = "bg:default fg:default"
format = "[via](fg:#94e2d5) [$symbol]($style) [$version](fg:#cdd6f4)"

[username]
format = "[   $user]($style) "
show_always = true
style_root = "bg:default fg:#f38ba8"
style_user = "bg:default fg:#cdd6f4"
